# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 24 Jan 2019 15:56:21 +0000
*	@ALL	1
*	@user	0
*	@cliente	1
*	@VIEWER	1
*	@REPORTER	2
*	@UPDATER	4
*	@DEVELOPER	16
*	@MANAGER	16
*	@ADMINISTRATOR	16
desenvolvimento:*	@ALL	0
desenvolvimento:*	@VIEWER	1
desenvolvimento:*	@REPORTER	2
desenvolvimento:*	@UPDATER	4
desenvolvimento:*	@DEVELOPER	16
desenvolvimento:*	@MANAGER	16
desenvolvimento:*	@ADMINISTRATOR	16
desenvolvimento:*	@cliente	0
sidebar	@cliente	0
sidebar	@ALL	0
wiki:*	@cliente	0
wiki:*	@ALL	0
