# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 24 Jan 2019 15:56:21 +0000
*	@ALL	1
*	@user	0
*	@cliente	1
*	@viewer	1
*	@reporter	2
*	@updater	4
*	@developer	8
*	@manager	16
*	@administrator	16
sidebar	@cliente	0
wiki:*	@cliente	0
wiki:*	@ALL	0
sidebar	@ALL	0
desenvolvimento:*	@ALL	0
