<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: nelson.pires
 * Date: Tue, 03 Nov 2020 11:02:07 -0200
 */

$conf['title'] = 'Base de Conhecimento - Cloudfy Systems';
$conf['lang'] = 'pt-br';
$conf['template'] = 'bootstrap3';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['toptoclevel'] = '2';
$conf['maxtoclevel'] = '5';
$conf['useheading'] = '1';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['authtype'] = 'authchained';
$conf['passcrypt'] = 'md5';
$conf['defaultgroup'] = 'cliente';
$conf['superuser'] = '@admin,@ADMINISTRATOR';
$conf['manager'] = '@MANAGER';
$conf['rememberme'] = 0;
$conf['disableactions'] = 'backlink,recent,revisions,register,resendpwd,profile_delete,rss,subscribe,unsubscribe,source,export_raw';
$conf['htmlmail'] = 0;
$conf['useslash'] = 1;
$conf['autoplural'] = 1;
$conf['defer_js'] = 0;
$conf['plugin']['authchained']['authtypes'] = 'authmantis:authpdo:authplain:authtoken';
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['authmantis']['dsn'] = 'pgsql:host=localhost;port=5432;dbname=bugtracker';
$conf['plugin']['authmantis']['user'] = 'mantis';
$conf['plugin']['authmantis']['pass'] = '<b>Y2Z5MjAxOA==';
$conf['plugin']['authmantis']['select-user'] = 'SELECT id AS uid,
       username AS user,
       realname AS name,
       password AS hash,
       email AS mail
  FROM mantis_user_table
 WHERE username = :user';
$conf['plugin']['authmantis']['select-user-groups'] = 'SELECT access_level AS group FROM mantis_user_table
 WHERE username = :user';
$conf['plugin']['authpdo']['dsn'] = 'pgsql:host=producao.ciktirq5ktik.sa-east-1.rds.amazonaws.com;port=5432;dbname=production';
$conf['plugin']['authpdo']['user'] = 'wiki';
$conf['plugin']['authpdo']['pass'] = '<b>Y2Z5QDI2NDUxMw==';
$conf['plugin']['authpdo']['select-user'] = 'SELECT AD010_NR_USR AS uid,
       AD010_VC_LOGIN AS user,
       AD010_VC_USR AS name,
       AD010_VC_PSW AS hash,
       AD010_VC_EMAIL AS mail,
(SELECT AD001_VC_EMPRESA FROM AD.AD001 INNER JOIN AD.AD008 ON(AD001_NR_EMPRESA = AD008_NR_EMPRESA) WHERE AD008_NR_USR = AD010_NR_USR LIMIT 1) AS branch
  FROM AD.AD010
 WHERE AD010_VC_LOGIN = :user';
$conf['plugin']['changes']['listmedia'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['discussion']['excluded_ns'] = '/(playground|wiki)/';
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['useavatar'] = 0;
$conf['plugin']['discussion']['subscribe'] = 0;
$conf['plugin']['discussion']['newestfirst'] = 1;
$conf['plugin']['discussion']['moderate'] = 1;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['discussion']['moderatorgroups'] = '@MANAGER';
$conf['plugin']['pageredirect']['show_note'] = 0;
$conf['plugin']['publish']['hide drafts'] = 1;
$conf['plugin']['publish']['hidereaderbanner'] = 1;
$conf['plugin']['publish']['hide_approved_banner'] = 1;
$conf['plugin']['tagging']['singleusermode'] = 1;
$conf['plugin']['translation']['translations'] = 'pt-br';
$conf['plugin']['translation']['display'] = 'langcode,flag,title';
$conf['plugin']['translation']['translateui'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cerulean';
$conf['tpl']['bootstrap3']['hideInThemeSwitcher'] = 'cosmo,cyborg,darkly,solar,slate,spacelab,superhero,united';
$conf['tpl']['bootstrap3']['sidebarShowPageTitle'] = 0;
$conf['tpl']['bootstrap3']['showTools'] = 'logged';
$conf['tpl']['bootstrap3']['individualTools'] = 1;
$conf['tpl']['bootstrap3']['showSearchForm'] = 'logged';
$conf['tpl']['bootstrap3']['showNavbar'] = 'logged';
$conf['tpl']['bootstrap3']['navbarLabels'] = 'login,register,tools';
$conf['tpl']['bootstrap3']['showPageId'] = 0;
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['useGoogleAnalytics'] = 1;
$conf['tpl']['bootstrap3']['googleAnalyticsTrackID'] = 'G-VRJ1PH1ZLE';
$conf['tpl']['bootstrap3']['googleAnalyticsAnonymizeIP'] = 1;
$conf['tpl']['bootstrap3']['googleAnalyticsNoTrackUsers'] = 1;
$conf['tpl']['bootstrap3']['browserTitle'] = '@TITLE@ [Cloudfy Wiki]';
$conf['tpl']['bootstrap3']['pageIcons'] = 'social-share,print';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['bootstrap3']['tagsOnTop'] = 0;
$conf['tpl']['bootstrap3']['useLocalBootswatch'] = '0';
$conf['tpl']['bootstrap3']['semantic'] = '0';
$conf['tpl']['bootstrap3']['fluidContainerBtn'] = '1';
$conf['tpl']['bootstrap3']['pageToolsAnimation'] = '0';
$conf['plugin']['googleanalytics']['GAID'] = 'G-VRJ1PH1ZLE';
$conf['plugin']['showpageafterlogin']['page_after_login'] = 'base_de_conhecimento:start';
